#!/bin/sh

echo '\n\n'
echo "Thank you for using SASS. In exchange for making my day a bit better, may a thousand virgins attend to your every whim."
echo '\n\n'
echo "Watching master.scss for changes..."

cd annotare/assets/css/
sass --watch master.scss:master.css
